language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t meraj90/docker-react -f Dockerfile.dev .

scrip:
  - docker run -e CI=true meraj90/docker-react npm run test -- --coverage